<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good) Exercises</span></div>

##### Exercise 1

| Term       | Brief description |
|:--|:--|
| Subsetting |*Extracting a portion / subset of the data*|
| Indexing   |Selecting one element|
| Slicing    |Selecting a range of elements|
| Masking    |Mask what is false and show what is true|

##### Exercise 2

In [2]:
import numpy as np

In [3]:
np_array_2d = np.array([[1, "A"], [3, "C"], [2, "B"], [4, "D"],
                        [5, "E"], [7, "G"], [6, "F"], [8, "H"],
                        [10, "J"], [9, "I"]])

In [4]:
#subsetting of array
np_array_integers = np_array_2d[0:10,0]
np_array_integers

array(['1', '3', '2', '4', '5', '7', '6', '8', '10', '9'], dtype='<U21')

In [5]:
#convert to integers
integers = np_array_integers.astype(int)
integers

array([ 1,  3,  2,  4,  5,  7,  6,  8, 10,  9])

In [6]:
#check which is odd and even
remainders = integers % 2
remainders

array([1, 1, 0, 0, 1, 1, 0, 0, 0, 1])

In [7]:
#masking
mask = remainders == 1
mask

array([ True,  True, False, False,  True,  True, False, False, False,
        True])

In [32]:
np_array_2d [mask,1]

array(['A', 'C', 'E', 'G', 'I'], dtype='<U21')