<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Need)</span></div>

# 1 Lists, Arrays & Dictionaries

## 1.1 Let’s compare

In [51]:
import numpy as np
# Different ways of storing data below↓

##### **Python lists**

In [52]:
alter_names = ['Gotchard', 'Majade', 'Valvarad']
real_names = ['Houtarou', 'Rinne', 'Supana']

##### **Numpy arrays**

In [53]:
alter_names_np = np.array(['Gotchard', 'Majade', 'Valvarad'])
real_names_np = np.array(['Houtarou', 'Rinne', 'Supana'])

##### **Dictionary**

In [54]:
info = {'Gotchard':'Houtarou', 'Majade': 'Rinne', 'Valvarad':'Supana'}

## 1.2 Accessing data from a list (or array)

In [55]:
#starts from 0th index ie. sth like 1st floor = GF, 2nd floor = level 1 in lifts heh

In [56]:
alter_names = ['Gotchard', 'Majade', 'Valvarad']
real_names = ['Houtarou', 'Rinne', 'Supana']

##### Example 1

In [57]:
alter_names[2]

'Valvarad'

##### Example 2

In [58]:
print(real_names[1], 'will cease to exist in', alter_names[0], "'s world.")

Rinne will cease to exist in Gotchard 's world.


##### Example 3

In [59]:
#Reverse index ie. start from the back / right, but this time 0th index doesn't apply, makes sense
alter_names[-1]
#Useful since the length can be unknown

'Valvarad'

## 1.3 Accessing data from a dictionary

In [60]:
info = {'Gotchard':'Houtarou', 'Majade': 'Rinne', 'Valvarad':'Supana'} 
#alter used as a key to unlock values
#no index for list
list(info)[0]

'Gotchard'

In [61]:
info['Gotchard']

'Houtarou'

In [62]:
info.keys() 

dict_keys(['Gotchard', 'Majade', 'Valvarad'])

In [63]:
info.values()

dict_values(['Houtarou', 'Rinne', 'Supana'])

In [64]:
#not in webpage
info.items()

dict_items([('Gotchard', 'Houtarou'), ('Majade', 'Rinne'), ('Valvarad', 'Supana')])

## 1.4 Higher dimensional lists

In [65]:
python_listing = [
    ['Gotchard', 'Houtarou'], 
    ['Majade', 'Rinne'], 
    ['Valvarad', 'Supana']
]

# 2 Lists vs. Arrays

In [66]:
py_list_2d = [
    [1, "A"], 
    [2, "B"], 
    [3, "C"], 
    [4, "D"],
    [5, "E"], 
    [6, "F"], 
    [7, "G"], 
    [8, "H"],
    [9, "I"], 
    [10, "J"]
]

np_array_2d = np.array(py_list_2d) #use phython list to create numpy array
print(np_array_2d)

[['1' 'A']
 ['2' 'B']
 ['3' 'C']
 ['4' 'D']
 ['5' 'E']
 ['6' 'F']
 ['7' 'G']
 ['8' 'H']
 ['9' 'I']
 ['10' 'J']]


## 2.1 Size

In [67]:
len(py_list_2d) #length of list

10

In [68]:
len(np_array_2d) #length of array

10

In [69]:
np_array_2d.shape #length & dimension of array

(10, 2)

In [70]:
py_list_3d = [
    [1, "A",'alpha'], 
    [2, "B",'beta'], 
    [3, "C",'charlie'], 
    [4, "D",'delta'],
    [5, "E",'echo'] 
]
np_array_3d = np.array(py_list_3d)

In [71]:
np_array_3d.shape

(5, 3)

## 2.2 Arrays are fussy about type

In [80]:
py_list = [1, 1.5, 'A']
np_array = np.array(py_list)

In [81]:
py_list

[1, 1.5, 'A']

In [82]:
np_array #all converted to strings, integers are not treated as numbers but as strings

array(['1', '1.5', 'A'], dtype='<U32')

## 2.3 Adding a number

In [83]:
py_list = [1, 4, 9, 16, 25]
np_array = np.array(py_list)

In [84]:
np_array + 10

array([11, 14, 19, 26, 35])

In [85]:
py_list + 10 #error

TypeError: can only concatenate list (not "int") to list

## 2.4 Adding another list

In [86]:
py_list_1 = [1, 4, 9, 16, 25]
py_list_2 = [1, 8, 27, 64, 125]

In [87]:
np_array_1 = np.array(py_list_1)
np_array_2 = np.array(py_list_2)

In [88]:
py_list_1 + py_list_2 #1 list is incorporated into another list

[1, 4, 9, 16, 25, 1, 8, 27, 64, 125]

In [89]:
py_list_1 - py_list_2 #error

TypeError: unsupported operand type(s) for -: 'list' and 'list'

In [90]:
np_array_1 - np_array_2

array([   0,   -4,  -18,  -48, -100])

In [91]:
np_array_1 + np_array_2 #addition of numbers respectively

array([  2,  12,  36,  80, 150])

## 2.5 Multiplying by a Number

In [92]:
py_list = [1, 4, 9, 16, 25]
np_array = np.array(py_list)     

In [93]:
py_list*2 #cause the number of elements in a list to double

[1, 4, 9, 16, 25, 1, 4, 9, 16, 25]

In [94]:
np_array*2 #multiplication of numbers

array([ 2,  8, 18, 32, 50])

## 2.6 Squaring

In [95]:
py_list = [1, 4, 9, 16, 25]
np_array = np.array(py_list)

In [96]:
np_array**2

array([  1,  16,  81, 256, 625])

In [97]:
py_list**2

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

## 2.7 Asking questions

In [98]:
py_list = [1, 4, 9, 16, 25]
np_array = np.array(py_list)    

In [99]:
py_list == 4 ##no answer to the question, arrays are needed to ask a question

False

In [100]:
np_array == 1 #Is this number 3?

array([ True, False, False, False, False])

In [101]:
np_array > 24   #Is this number greater than 3?

array([False, False, False, False,  True])

## 2.8 Mathematics

In [102]:
py_list = [1, 4, 9, 16, 25]
np_array = np.array(py_list) 

##### List

In [103]:
sum(py_list) #summation

55

In [104]:
max(py_list) #maximum

25

In [105]:
min(py_list) #minimum 

1

##### Arrays

In [106]:
np_array.sum() #way faster than sum(np_array)

55

In [107]:
np_array.max()

25

In [108]:
np_array.min()

1

In [109]:
np_array.mean() ###more things can be done with arrays

11.0

In [110]:
np_array.std() ###Standard deviation, not used for lists <- create list, convert to arrays, use for mathematical functions
#arrays do not grow as fast as lists

8.648699324175862