<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good)</span></div>

# What to expect in this chapter

# Subsetting: Indexing and Slicing

In [1]:
import numpy as np

## 1.1 Lists & Arrays in 1D | Subsetting & Indexing

In [108]:
## IGNORE: Note - Keyboard shortcuts under Help
#To extract items: a) subsetting, b) indexing, c) slicing

x=["a1", "b2", "c3", "d4", "e5",
         "f6", "g7", "h8", "i9", "j10"] #Python list

In [5]:
x[2:6] #starts at index 2 ie. c3, and contains 6-2=4 elements

['c3', 'd4', 'e5', 'f6']

In [7]:
x[2:6:2] #starts at index 2 ie. c3, and will give the element in steps of 2 within 6-2=4 elements

['c3', 'e5']

In [11]:
x[2:6:1] #so this gives the same elements as x[2:6]

['c3', 'd4', 'e5', 'f6']

In [14]:
x[3:] #will give len(x)-3 elements, starting from d4

['d4', 'e5', 'f6', 'g7', 'h8', 'i9', 'j10']

In [16]:
x[3::-1] #opposite of previous cell

['d4', 'c3', 'b2', 'a1']

In [109]:
x[:6] #will give 6-0 elements

['a1', 'b2', 'c3', 'd4', 'e5', 'f6']

In [21]:
x[:6:-1]

['j10', 'i9', 'h8']

In [22]:
x[::-2]

['j10', 'h8', 'f6', 'd4', 'b2']

## 1.2 Arrays only | Subsetting by masking

In [23]:
np_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

In [111]:
my_mask = np_array < 3
my_mask

array([ True,  True, False, False, False, False, False, False, False,
       False])

In [112]:
#masking -- show me all the true, don't show me the false まさに逆仮面
np_array[my_mask]

array([1, 2])

In [113]:
np_array[np_array == 3]

array([3])

##### Example 1

In [114]:
#inverting a mask using '~'; 'NOT' gate
np_array[~(np_array == 3)]

array([ 1,  2,  4,  5,  6,  7,  8,  9, 10])

##### Example 2

In [115]:
#and using '&'; will give what overlaps
np_array[(np_array < 3) & (np_array>8)]

array([], dtype=int64)

In [116]:
np_array[~((np_array < 3) & (np_array>8))]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

##### Example 3

In [117]:
#or using '|'
np_array[(np_array < 3) | (np_array > 8)] # '|' means 'OR'

array([ 1,  2,  9, 10])

## 1.3 Lists & Arrays in 2D | Indexing & Slicing

In [118]:
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]

np_array_2d = np.array(py_list_2d)
#diff between arrays and lists, numpy converts all to strings

##### Example 1

In [57]:
py_list_2d[-1]

[10, 'J']

In [55]:
np_array_2d[-1]

array(['10', 'J'], dtype='<U21')

In [61]:
np_array_2d[1:5]

array([['2', 'B'],
       ['3', 'C'],
       ['4', 'D'],
       ['5', 'E']], dtype='<U21')

In [62]:
np_array_2d[1:5:-1]

array([], shape=(0, 2), dtype='<U21')

##### Example 2

In [63]:
##In the case where more than 1 element is present at 1 index / position
py_list_2d[3][1]

'D'

In [64]:
np_array_2d[3,1]

'D'

##### Example 3

In [68]:
py_list_2d[1:5]

[[2, 'B'], [3, 'C'], [4, 'D'], [5, 'E']]

In [67]:
np_array_2d[1:5]

array([['2', 'B'],
       ['3', 'C'],
       ['4', 'D'],
       ['5', 'E']], dtype='<U21')

##### Example 4 and 5

In [121]:
py_list_2d[:5][0] #will be the [1, 'A']
py_list_2d[1:5][0] #used when you want to know what is in the first position in the list

[2, 'B']

In [120]:
np_array_2d[:5, 0] #will include the first
np_array_2d[1:5, 0] #used when you want to know what is the first element in each index in the array

array(['2', '3', '4', '5'], dtype='<U21')

## 1.4 Growing lists

##### Example 1

In [77]:
x=[3,2,5,6]*3
x

[3, 2, 5, 6, 3, 2, 5, 6, 3, 2, 5, 6]

##### Example 2

In [80]:
x=[1]
x= x + [3,4]
x= x + [6,10,22,12]
x= x + [11]
x

[1, 3, 4, 6, 10, 22, 12, 11]

In [81]:
x=[1]
x+= [3,4]
x+= [6,10,22,12]
x+= [11]
x

[1, 3, 4, 6, 10, 22, 12, 11]

In [85]:
x=[1]
x.append(2)
x.append(3)
x.append(43)
x

[1, 2, 3, 43]

##### Example 3

In [86]:
x = [1, 2, 3]
x += [4, 5, 6]
x

[1, 2, 3, 4, 5, 6]

In [87]:
x=[1, 2, 3]
x.extend([4, 5, 6]) #does it how you want
x

[1, 2, 3, 4, 5, 6]

In [89]:
x=[1, 2, 3]
x.append([4, 5, 6]) #just puts the list in; use this when you want to add lists to list?; as its name suggest, adding as sth extra
x

[1, 2, 3, [4, 5, 6]]

# Some loose ends

## 1.5 Tuples

In [ ]:
##lists can be modified, but not tuples

In [90]:
#tuples need to be defined
x = (1,4, 9, 16, 25)

In [94]:
print(x[2]) #ie. indexing

9


In [96]:
# Tuples cannot change
x[0]=-2
x[0]/= [10]

TypeError: 'tuple' object does not support item assignment

## 1.6 Be VERY careful when copying

In [102]:
## To copy lists from x to y and z,
x_lists=[1, 2, 3]
y=x_lists
z=x_lists #would be better to do this instead↓  

In [104]:
print(f'{id(x_lists)=}, {id(y)=}, {id(z)=}') #all the ids are the same

id(x_lists)=4411331712, id(y)=4411331712, id(z)=4411331712


In [105]:
x_lists=[1, 2, 3]
y=x_lists.copy()
z=x_lists.copy()
y

[1, 2, 3]

In [107]:
print(f'{id(x_lists)=}, {id(y)=}, {id(z)=}') #all the ids are different, which is supposedly better and impt than having all same ids

id(x_lists)=4577751104, id(y)=4411331904, id(z)=4571775104
